# Site settings
title: David B. Bracewell
email: first@firstlast.com
description: ""
baseurl: ""
url: "http://dbracewell.github.io"
twitter_username: DavidBracewell
github_username:  dbracewell

# Build settings
markdown: redcarpet
permalink: pretty
